<?php

namespace Runator\TradBundle\Repositories;

use Doctrine\ORM\EntityRepository;
use Runator\TradBundle\Entity\Translate as Translate;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslateRepository extends EntityRepository
{

}
